services:
  app:
    build: .
    image: carebridge-api-app:latest
    ports:
      - '8080:8080'
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

networks:
  app-network:
    driver: bridge
