name: carebridge_theme
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  google_fonts: ^6.2.1

  carebridge_models:
    path: ../carebridge_models
    # git: https://github.com/your-repo/carebridge_models.git
    # ref: main

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
