name: carebridge_models
description: "Carebridge Mobile module"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  hive_generator: ^2.0.1
  flutter:
    sdk: flutter
    # commons:
    #   path: ../commons
    # git: 
    #   url: git@github.com:Hidup-Sehat-Bahagia-Kaya-Raya/my_chauffeur_commons.git
    #   ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^6.0.0
  build_runner: ^2.4.15

flutter:
