export const AppColors = {
    primary: {
        50: "var(--color-primary-50)",
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
    },
    secondary: {
        50: "var(--color-secondary-50)",
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
    },
    neutral: {
        0: "var(--color-neutral-0)",
        10: "var(--color-neutral-10)",
        20: "var(--color-neutral-20)",
        30: "var(--color-neutral-30)",
        40: "var(--color-neutral-40)",
        50: "var(--color-neutral-50)",
        60: "var(--color-neutral-60)",
        70: "var(--color-neutral-70)",
        80: "var(--color-neutral-80)",
        90: "var(--color-neutral-90)",
        100: "var(--color-neutral-100)",
    },
    info: {
        0: "var(--color-info-0)",
        10: "var(--color-info-10)",
        20: "var(--color-info-20)",
        30: "var(--color-info-30)",
        40: "var(--color-info-40)",
    },
    success: {
        0: "var(--color-success-0)",
        10: "var(--color-success-10)",
        20: "var(--color-success-20)",
        30: "var(--color-success-30)",
        40: "var(--color-success-40)",
    },
    warning: {
        0: "var(--color-warning-0)",
        10: "var(--color-warning-10)",
        20: "var(--color-warning-20)",
        30: "var(--color-warning-30)",
        40: "var(--color-warning-40)",
    },
    error: {
        0: "var(--color-error-0)",
        10: "var(--color-error-10)",
        20: "var(--color-error-20)",
        30: "var(--color-error-30)",
        40: "var(--color-error-40)",
    },
    gradient: {
        0: "var(--color-gradient-0)",
        10: "var(--color-gradient-10)",
    },
    background: "var(--color-background)",
    foreground: "var(--color-foreground)",
};