name: carebridge_commons
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.12.30
  carebridge_models:
    path: ../carebridge_models
  carebridge_theme:
    path: ../carebridge_theme
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
