name: model
description: Carebridge Mobile module
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  copy_with_extension: ^6.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  hive_generator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^6.0.0
  build_runner: ^2.4.15

flutter:

